# Generated by Django 3.2.19 on 2023-05-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='schedule_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
